### ISSUE TITLE
listen doesn't catch the event (I've joined to the channel) - Angular 9

### ISSUE THREAD

**Issue by csimpi** [chancezeus/angular-laravel-echo#13]
Hi, thx for this wrapper.

I use Angular 8, installed the ngx-laravel-echo package. Everything seems fine, I can see that the client connected, joined to the channel, and also I can see the event has been fired in laravel-echo-server's console, but on client side it seems I can't catch the event.

In my contoller:

```
  ngOnInit() {
    if(this.EchoService.connected){
      this.EchoService.join('test-channel','public');
      this.EchoService.listen('test-channel', 'App\\Events\\UserPostUpload').subscribe( data =>
          {console.log('MSG:',data);}
      );
    }


  }
```

In laravel-server's console:
```
Console: [08:42:48] - xxxxxxxxxxxxxxxxx joined channel: test-channel
Channel: test-channel
Event: App\Events\UserPostUpload
```

Excepted result:
`MSG: {foo:bar}` appears in the clients' JavaScript console

Current result:
Nothing happens

**Comment by csimpi** [comment]
In the meantime, I realized I should listen `UserPostUpload` instead of `App\\Events\\UserPostUpload`.
It works well now.

**Comment by satish666** [comment]
@csimpi  I am working with this package  I need some help . 
My `this.EchoService.connected` is returning false 
`export const echoConfig: EchoConfig = {
  userModel: 'App\\models\\v1\\admin\\Auth\\AdminUser',
  notificationNamespace: '',
  options: {
      broadcaster: 'pusher',
      host: 'http://localhost:8000',
      namespace: 'App\\Events',
    client: new Pusher('websocketkey',
      {
        authEndpoint: 'http://localhost:8000/broadcasting/auth',
        enabledTransports: ['ws', 'wss'], //fixes connection issues
        wsHost: '127.0.0.1',
        wsPort: 6001,
        disableStats: true,
      })
  }
};`  
This is my config file

**Comment by GlauberF** [comment]
@csimpi how do you connect, why after I connect, if I access **this.EchoService.connected** variable, it is always false.

would you have any example to share :)?
